@startuml
!include style.puml

start
:User inputs a command;

:Logic component passes clock to AddressBookParser;

:Type of command determined;

:Parser instantiated;

If () then ([Clock-Dependent])

:Clock passed to command-specific parser;

:Parser extracts current time from clock;


else ([else])
endif

:Parser extracts parameters from command;
:Command executed (including data updates);
:Results are displayed to user
(Including modified Person data, if applicable);

stop
@enduml
