@startuml
!include style.puml

start
:User inputs mark command;

:Parser parses command;

If () then ([Command is valid format])

If () then ([Person index exists])
    :Marks the person at specified index;
    :Returns success message;
else ([else])
    :Returns failure message
    (Invalid index);
endif
:LogicManager prints message to user;

else ([else])
    :Returns failure message
    (invalid command format);

endif

:Results are displayed to user;

stop
@enduml
